// Generated by scripts/build.py: compatibility with previously shared album URLs.
(() => {
const routes = {"co_mhr": "albums/co_mhr.html", "co_rct": "albums/co_rct.html", "rugby": "albums/rugby.html", "mariage": "albums/mariage.html", "concertsinfonia": "albums/concertsinfonia.html", "noel": "albums/noel.html", "Argentique": "albums/Argentique.html", "argentique_toulouse": "albums/argentique_toulouse.html", "montagne": "albums/montagne.html", "autres": "albums/autres.html"};
const id = new URLSearchParams(location.search).get('id');
if (id && Object.prototype.hasOwnProperty.call(routes, id)) location.replace(routes[id]);
else if (id) { document.getElementById('gallery-heading').textContent = 'Album introuvable'; document.getElementById('gallery-message').textContent = 'Cette adresse ne correspond à aucun album. Choisissez un reportage ci-dessous.'; }
})();
